-- Supabase Migration: 002_llm_usage.sql
-- Add schema for LLM observability and versioning.

-- 1. feed_events table columns
ALTER TABLE feed_events ADD COLUMN IF NOT EXISTS model_version TEXT;
ALTER TABLE feed_events ADD COLUMN IF NOT EXISTS prompt_version TEXT;

-- 2. decision_commits table columns
ALTER TABLE decision_commits ADD COLUMN IF NOT EXISTS model_version TEXT;
ALTER TABLE decision_commits ADD COLUMN IF NOT EXISTS prompt_version TEXT;

-- 3. llm_call_usage table
CREATE TABLE IF NOT EXISTS llm_call_usage (
    id                      INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ts                      TIMESTAMPTZ NOT NULL,
    task                    TEXT    NOT NULL,
    provider                TEXT    NOT NULL,
    model                   TEXT    NOT NULL,
    tick_ts                 TIMESTAMPTZ,
    mint_address            TEXT,
    status                  TEXT    NOT NULL,
    latency_ms              INTEGER,
    input_tokens            INTEGER,
    cache_hit_tokens        INTEGER,
    output_tokens           INTEGER,
    total_tokens            INTEGER,
    estimated_cost_usd      REAL,
    is_peak_window          INTEGER NOT NULL DEFAULT 0,
    degradation_reason      TEXT
);

CREATE INDEX IF NOT EXISTS idx_llm_call_usage_ts ON llm_call_usage(ts);
